# Configuration Settings for ZED-F9P device
debug: 4                 # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyUSB0     # ZED-F9P rover serial port
frame_id: gps

config_on_startup: false # use chip config

uart1:
  baudrate: 38400       # serial port baudrate
  in: 32
  out: 3

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
  rxm:
    all: false
    raw: true           # publish rxmraw or rxmrawx base on f9p feature

